### ISSUE TITLE
Multiple queue wokers

### ISSUE THREAD

**Issue by kak2z7702** [amranidev/micro-bus#16]
Hi. I can have more than 500 messages in sqs in one minute. I want to set up for my subscriber multiple workers to process for one sqs. How can I do this? There is not a word about this in the documentation) Thank you.

**Comment by amranidev** [comment]
Hey @kak2z7702 - There is a solution for that. if you're expecting to have more than 500 messages in the queue at once then you will have to consider to configure the supervisor in your servers. you can specify how much replicated processes you want. `numprocs=10`

in your supervisor configuration file.

```
[program:application]
process_name=%(program_name)s_%(process_num)02d
command=php /your-laravel-application-path/artisan queue:work subscriber --tries=6
autostart=true
autorestart=true
numprocs=10
```

**Comment by kak2z7702** [comment]
thank you so much.
