### ISSUE TITLE
Make Sns Client profile configurable

### ISSUE THREAD

**Issue by gabrielboliveira** [amranidev/micro-bus#7]
I see that on the SnsConnector class, the profile is being hardcoded to `default`. 

https://github.com/amranidev/micro-bus/blob/0843bbfb5707dac1e50a1799eca0b739fecd3c7e/src/Sns/SnsConnector.php#L36 

But, if the user specified is an IAM role, the there will be an error:
```
Aws/Exception/CredentialsException with message 'Cannot read credentials from /root/.aws/credentials'
```

I suggest that you move the profile configuration to `publisher.php`, under sns:

```
    'sns'    => [
        'profile' => 'default',
        'key'    => env('PUBLISHER_SNS_KEY'),
        'secret' => env('PUBLISHER_SNS_SECRET'),
        'region' => env('PUBLISHER_SNS_REGION'),
    ],
```

So if anyone wants to use a IAM Role user (no login, just CLI and SDKs), they still can. Related: https://stackoverflow.com/a/47805400

**Comment by gabrielboliveira** [comment]
Sorry, I see that adding the profile key to sns on `publisher.php` already overrides that option, so perhaps its just a matter of updating the README?

**Comment by amranidev** [comment]
@gabrielboliveira can you please create a PR for that?
